### ISSUE TITLE
feedback: on installing ramda

### ISSUE THREAD

**Issue by twilson63** [rpearce/ramda.guide#13]
* You may want to consider showing different ways to install ramda, node, browser, or deno?

* Or you may want add a note, that nodejs/npm (version) is recommended to be installed https://github.com/rpearce/ramda.guide/blob/main/src/book/including-ramda.md

``` js
import * as R from 'https://cdn.skypack.com/ramda'

const { add } = R

console.log(add(1,2))
```

**Comment by rpearce** [comment]
Great feedback! Gotta know how to get the thing in all the ways.

Should I write this out myself or link to installation instructions from official places? For example, from https://ramdajs.com:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/592876/128721644-fff21518-fd24-44fb-947a-9561a652a558.png">

And from the deno ramda package, https://deno.land/x/ramda@v0.27.2:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/592876/128721815-e6d81f89-aa27-4a30-bd7b-239bea84d798.png">

**Comment by igreulich** [comment]
Hmmm, I would think linking to the official docs would be enough. But that depends on who your intended audience is. If you are 'talking' to @twilson63 or I, we would need less instruction than if you were talking to a brand new developer.

Either way It is very much worth talking about the set up you will be using for the code examples regardless of what it is [node/deno, js/ts, etc], just to set expectations for how things will be presented.
